#ifndef H_CONSTANTS
    #define H_CONSTANTS

#define FILENAME_HIGH_SCORES "scores.txt"
#define FILENAME_CONFIG "config.bin"

#define MAX_X_TELA 80
#define MAX_Y_TELA 25

#define OFFSET_X 1
#define OFFSET_Y 2

#define LINHA_INICIO_MENU 15

#define MAX_STRINGS_MENU 20
#define MAXSIZE_STRINGS_MENU 20

#define NUM_OPCOES 5

#define NOVO_JOGO 0
#define HIGH_SCORES 1
#define OPCOES 2
#define CREDITOS 3
#define SAIR 4

#define COLUNA_INICIO_MENU_OPCOES 35

#define NUM_OPCOES_CONFIG 4

#define MENU_CONFIG_VELOCIDADEINICIAL 0
#define MENU_CONFIG_MAXTAMANHO 1
#define MENU_CONFIG_MAXITENS 2
#define MENU_CONFIG_VOLTAR 3

#define MIN_VELOCIDADEINICIAL 1
#define MAX_VELOCIDADEINICIAL 10
#define MIN_MAXTAMANHO 10
#define MAX_MAXTAMANHO 100
#define MIN_MAXITENS 1
#define MAX_MAXITENS 10

#define VELOCIDADEINICIAL_PADRAO 5
#define MAXTAMANHO_PADRAO 20
#define MAXITENS_PADRAO 5

#define MAX_NOME 3
#define NUM_HIGH_SCORES 10
#define MAXSIZE_STRING_HIGHSCORES 15
#define LINHA_NOME_HIGHSCORE 22
#define COLUNA_NOME_HIGHSCORE 38

#define LINHA_INICIO_HIGH_SCORES 12
#define COLUNA_INICIO_HIGH_SCORES 30

#define LINHA_INICIO_FIMCENARIO 11
#define LINHA_FIM_FIMCENARIO 20
#define COLUNA_INICIO_FIMCENARIO 25
#define COLUNA_FIM_FIMCENARIO 65

#define LINHA_MSG_FIMCENARIO 12
#define COLUNA_MSG_FIMCENARIO 36
#define LINHA_PONTUACAO_FIMCENARIO 14
#define COLUNA_PONTUACAO_FIMCENARIO 30
#define LINHA_SAIR_FIMCENARIO 18
#define COLUNA_SAIR_FIMCENARIO 33

#define LINHA_INICIO_ENTRAHIGHSCORE 20
#define LINHA_FIM_ENTRAHIGHSCORE 24
#define COLUNA_INICIO_ENTRAHIGHSCORE 25
#define COLUNA_FIM_ENTRAHIGHSCORE 65

#define MAXSIZE_MSGS_FIMCENARIO 50

#define UM_SEGUNDO_EM_MS 1000

#define NUM_CENARIOS 3
#define LINHAS_CENARIO 24
#define COLUNAS_CENARIO 80

#define MAX_SNAKE 80
#define INI_X_SNAKE 20
#define INI_Y_SNAKE 12
#define INI_TAM_SNAKE 5

#define TECLADO_ESTENDIDO 224

#define ASCII_CIMA 72
#define ASCII_BAIXO 80
#define ASCII_DIREITA 77
#define ASCII_ESQUERDA 75

#define ASCII_ENTER 13

#define ASCII_SPACEBAR 32
#define ASCII_ESC 27

#define BACK_CENARIO 6
#define BACK_SNAKE 2

#define PTS_BASE_COMIDA 2
#define PTS_BASE_SLOWER 1
#define PTS_BASE_FASTER 3
#define PTS_BASE_SKIP 40
#define BONUS_COMPLETA_CENARIO 1000

#define GAME_OVER 1
#define CENARIO_COMPLETO 2
#define USER_EXIT 3

// Cores

// Conio2
#define COR_TITULO 2  // GREEN
#define COR_MOLDURA 2  // GREEN
#define COR_BG_CENARIO 6  // BROWN
#define COR_BG_MENU_SELECIONADO 0  // BLACK
#define COR_TEXTO_MENU_SELECIONADO 10  // LIGHTGREEN
#define COR_TEXTO_PADRAO 0  // BLACK
#define COR_TEXTO_TOPSCORES 15  // WHITE
#define COR_BG_PRIMEIRO 10  // LIGHTGREEN
#define COR_BG_SEGUNDO 3  // CYAN
#define COR_BG_TERCEIRO 2  // GREEN
#define COR_BG_MSG 15  // WHITE


#endif // H_CONSTANTS
